install:
	npm i

start:
	npm start

build:
	npm run build

lint:
	npx eslint --ext js,jsx --no-eslintrc --config .eslintrc.yml .

lint-fix:
	npx eslint --ext js,jsx --no-eslintrc --config .eslintrc.yml . --fix